# Generated by Django 5.2 on 2025-04-21 12:31

from django.db import migrations, models
from django.contrib.auth.hashers import make_password


def convert_email_to_username(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        # Use email prefix as username, fallback to user_id if email is None
        if user.email:
            base_username = user.email.split('@')[0]
        else:
            base_username = f'user_{user.id}'
            
        # Ensure username is unique by adding a number if needed
        username = base_username
        counter = 1
        while User.objects.filter(username=username).exists():
            username = f"{base_username}_{counter}"
            counter += 1
            
        user.username = username
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.RunPython(convert_email_to_username),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
