# Generated by Django 5.2 on 2025-04-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_convert_email_to_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default="user", max_length=150, unique=True),
        ),
    ]
